#!/usr/bin/env ruby


# Problem 2 from projecteuler.net
# 
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms

MAX_NUM = 4_000_000
fibonacci_number = 1
prev_fibonacci_number = 1
even_numbered_total = 0
ctr = 0

while true == true
  prev_fibonacci_number, fibonacci_number = fibonacci_number, prev_fibonacci_number + fibonacci_number 
  break if fibonacci_number > MAX_NUM
  even_numbered_total += fibonacci_number if fibonacci_number % 2 == 0  
  printf "total is %9i, fibonacci # is %9i\n",
         even_numbered_total, fibonacci_number
end
